// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package repo

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (thread_id, sender, content)
VALUES ($1, $2, $3)
RETURNING id, thread_id, sender, content, created_at
`

type CreateMessageParams struct {
	ThreadID string `json:"thread_id"`
	Sender   string `json:"sender"`
	Content  string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ThreadID, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO "thread" (thread_name)
VALUES ($1)
RETURNING id, thread_name, created_at
`
type CreateThreadParams struct{
	ThreadName string `json:"thread_name"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams ) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.ThreadName)
	var i Thread
	err := row.Scan(&i.ID, &i.ThreadName, &i.CreatedAt)
	return i, err
}

const editMessageByID = `-- name: EditMessageByID :one
UPDATE message
SET sender = $2,
    content = $3
 WHERE id = $1
 RETURNING id, thread_id, sender, content, created_at
`

type EditMessageByIDParams struct {
	ID      string `json:"id"`
	Sender  string `json:"sender"`
	Content string `json:"content"`
}

func (q *Queries) EditMessageByID(ctx context.Context, arg EditMessageByIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, editMessageByID, arg.ID, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, thread_id, sender, content, created_at FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByThread = `-- name: GetMessagesByThread :many
SELECT id, thread_id, sender, content, created_at FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessagesByThread(ctx context.Context, threadID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
