// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) ([]Customer, error)
	CreateOrders(ctx context.Context, arg CreateOrdersParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) ([]Product, error)
	GetCustomerByID(ctx context.Context, id string) (Customer, error)
	GetProductByID(ctx context.Context, id string) ([]Product, error)
	UpdateOrdersByID(ctx context.Context, arg UpdateOrdersByIDParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
